version: '3'

services:
  zookeeper:
    container_name: my_zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka01:
    container_name: kafka_node_01
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka02:
    container_name: kafka_node_02
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka03:
    container_name: kafka_node_03
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka03:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    container_name: kafka_producer
    image: crispar/remote-dev_env:0.1
    depends_on:
      - kafka01
      - kafka02
      - kafka03
    environment:
      KAFKA_BROKER_LIST: "kafka01:9092,kafka02:9093,kafka03:9094"
      TOPIC: "test_topic"

  consumer:
    container_name: kafka_consumer
    image: crispar/remote-dev_env:0.1
    depends_on:
      - kafka01
      - kafka02
      - kafka03
    environment:
      KAFKA_BROKER_LIST: "kafka01:9092,kafka02:9093,kafka03:9094"
      TOPIC: "test_topic"

